server:
  port: 8080
 
spring:
  datasource:
    username: root
    password: "0000"
    url: jdbc:mysql://localhost:3306/userdb?characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
 
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.entity
 
#showSql
logging:
  level:
    com:
      example:
        mapper : debug